site_name: Tietoliikenneohjelmointi

theme:
  name: material
  language: fi
  features:
    - content.code.copy     # add copy button to code blocks
    - content.code.annotate # add annotation support to code blocks
    - content.tabs.link     # content tabs united!
  # Day and night mode
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Emojis and icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Mermaid graphs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Keyboard key symbols
  - pymdownx.keys
  # Mark text by wrapping it between dual pairs of = symbols
  - pymdownx.mark
  # Admonition call-outs such as "!!! note", and support for making call-outs collapsible
  - admonition
  - pymdownx.details
  # Footnotes
  - footnotes
  # Checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  # Navigation page ordering
  - awesome-nav
  - search




copyright: |
  Copyright &copy; 2025 <a href="https://www.kamk.fi">Kajaanin Ammattikorkeakoulu Oy</a>. 
  Licenced under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">BY-NC-SA 4.0</a>